#!/usr/bin/lua
local cmds = require("dottodo_commands")

-- cmd list
--[[
  print -> print the .todo file
  append [ tag ] <todo>
  delete <regexp>
]]

local err = nil
-- ignore the args for now
cmd = arg[1]

if cmd == "print" then
   cmds.print( arg[2] or "." )
end
